In [13]:
profil = ['Ihsan','2021071005','Informatika','DAA','14/09/22','UPJ']
for item in profil:
    print(item)

Ihsan
2021071005
Informatika
DAA
14/09/22
UPJ


In [14]:
print(profil[1])

2021071005


In [15]:
print(profil[-1])

UPJ


In [16]:
print(profil[1:3])

['2021071005', 'Informatika']


In [17]:
for item in profil:
    print('UPJ ' + item)

UPJ Ihsan
UPJ 2021071005
UPJ Informatika
UPJ DAA
UPJ 14/09/22
UPJ UPJ


In [18]:
skin = ['Reaver','Glitchpop','RGX','Origin']
print(skin[0])
print(skin[2])
print(skin[1])
print(skin[3])

Reaver
RGX
Glitchpop
Origin


In [19]:
print(skin[0:3])

['Reaver', 'Glitchpop', 'RGX']


In [20]:
for item in skin:
    print(item + ' GG')

Reaver GG
Glitchpop GG
RGX GG
Origin GG


In [21]:
tuple_skin = ('Reaver','Glitchpop','RGX','Origin')
print(tuple_skin[1])

Glitchpop


In [22]:
UPJ = ('universitas','pembangunan','jaya')
print(UPJ)

('universitas', 'pembangunan', 'jaya')


In [23]:
angka = ((100,),(200,400,600),(300,),(400,800))
print(angka)

((100,), (200, 400, 600), (300,), (400, 800))


In [24]:
profil_mahasiswa = {'Nama' : 'Ihsan','NIM' : '2021071005','Prodi' : 'Informatika','Universitas' : 'UPJ'}
print(profil_mahasiswa)

{'Nama': 'Ihsan', 'NIM': '2021071005', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [25]:
profil_mahasiswa.get('Nama')

'Ihsan'

In [26]:
profil_mahasiswa['Prodi']='Sistem Informasi'
print(profil_mahasiswa)

{'Nama': 'Ihsan', 'NIM': '2021071005', 'Prodi': 'Sistem Informasi', 'Universitas': 'UPJ'}


In [27]:
prodi = {'informatika','sistem informasi','DKV'}
print(prodi)

{'sistem informasi', 'informatika', 'DKV'}


In [28]:
dish = {'jelly','soes','pudding','jelly'}
print(dish)

{'pudding', 'jelly', 'soes'}


In [29]:
yellow = {'rose','blood','firehydrants','leaves'}
red = {'dandelions','leaves','firehydrants'}
print (yellow|red)
print (yellow&red)

{'blood', 'firehydrants', 'dandelions', 'leaves', 'rose'}
{'firehydrants', 'leaves'}


In [30]:
import pandas as pd
import numpy as np

In [31]:
df = pd.DataFrame([
['1', 'Fares', 32, True],
['2', 'Elena', 23, False],
['3', 'Steven', 40, True]])
print(df)

   0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True


In [32]:
df.columns = ['id','name','age','decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


In [43]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [44]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [45]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [46]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [47]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [53]:
mhs = pd.DataFrame([
['1', 'Informatika', 50, 30, 20],
['2', 'Sistem Informasi', 55, 30, 25],
['3', 'Teknik Sipil', 40, 30, 10]])
mhs.columns = ['No','Prodi','Mahasiswa','Lakilaki','Perempuan']
print(mhs)

  No             Prodi  Mahasiswa  Lakilaki  Perempuan
0  1       Informatika         50        30         20
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10


In [33]:
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)
print(type(myMatrix))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [34]:
Matrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(Matrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


In [56]:
myVector = [22,33,44,55]
print(myVector)
print(type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [57]:
myVector = np.array([22,33,44,55])
print(myVector)
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [35]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-I]
  def size(self):
    return len(self.items)

In [36]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

print(stack.pop())

print(stack.isEmpty())

Yellow
False


In [37]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [38]:
queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [39]:
print(queue.dequeue())
print(queue.dequeue())

Red
Green
